# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TechnicalTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'

  # Pods for TechnicalTest

  target 'TechnicalTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
